### ISSUE TITLE
invalid format string: 'return %)('

### ISSUE THREAD

**Issue by HakHakopyan** [bennyhuo/KotlinDeepCopy#9]
Try to use DeepCopy, but has next error:
```
Caused by: java.lang.IllegalArgumentException: invalid format string: 'return %)('
	at com.squareup.kotlinpoet.CodeBlock$Builder.addArgument(CodeBlock.kt:347)
	at com.squareup.kotlinpoet.CodeBlock$Builder.add(CodeBlock.kt:317)
	at com.squareup.kotlinpoet.CodeBlock$Builder.addStatement(CodeBlock.kt:413)
	at com.squareup.kotlinpoet.FunSpec$Builder.addStatement(FunSpec.kt:441)
	at com.bennyhuo.kotlin.deepcopy.compiler.DeepCopyGenerator.generate(DeepCopyGenerator.kt:65)
	at com.bennyhuo.kotlin.deepcopy.compiler.DeepCopyProcessor.process(DeepCopyProcessor.kt:45)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:89)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:166)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:980)
```

**Comment by bennyhuo** [comment]
Could you provide a demo to reproduce the problem?

**Comment by bennyhuo** [comment]
Fixed by updating kotlin metadata library.
